In [34]:
import pandas as pd

alfafam1 = pd.DataFrame(pd.read_csv('alfafa-23-10-25/altura_alfafa_23_10_25.csv', sep=";", encoding='latin1'))
alfafam2 = pd.DataFrame(pd.read_csv('alfafa-23-11-25/Alturas_alfafa.csv', sep=";", encoding='latin1'))
df3 = pd.DataFrame(pd.read_csv('alfafa-23-11-25/Alturas_alfafa2.csv', sep=";", encoding='latin1'))
df4 = pd.DataFrame(pd.read_csv('alfafa-23-11-25/Pmassa_alfafa.csv', sep=";", encoding='latin1'))


display(1)
# display(df4)

1

In [35]:
merge = pd.concat([alfafam1, alfafam2], ignore_index=True)
merge.insert(1, 'Cultivar', merge['ALTURA'].str[0:2])
display(merge)

   ALTURA Cultivar     1     2     3     4     5  MÃ©dia
0    CR01       CR  30.2  28.9  27.7  25.5  26.4    27.7
1    CR02       CR  25.4  33.1  26.5  30.4  32.3    29.5
2    CR03       CR  29.5  27.5  25.2  30.9  28.2    28.3
3    CR04       CR  37.1  35.5  32.0  34.1  32.1    34.2
4    CR05       CR  38.0  29.6  37.5  34.4  38.5    35.6
..    ...      ...   ...   ...   ...   ...   ...     ...
75   TR16       TR  40.0  49.1  39.3  32.0  44.2    40.9
76   TR17       TR  41.0  56.2  54.5  50.0  51.0    50.5
77   TR18       TR  44.2  50.1  51.2  48.5  41.0    47.0
78   TR19       TR  45.2  39.7  38.5  42.0  38.5    40.8
79   TR20       TR  40.1  43.2  49.5  50.1  47.3    46.0

[80 rows x 8 columns]

In [33]:
merge["PARCELA"] = merge["ALTURA"].str[:4]

# Fazer o merge
df_final = merge.merge(
    df4,
    on="PARCELA",
    how="left"
)

display(df_final)

df_final.to_csv('dataset/metadata.csv', sep=";", index=False, encoding='latin1')

,ALTURA,Cultivar,1,2,3,4,5,MÃ©dia,PARCELA,K2O (kg/ha),MS (kg/ha)
0,CR01,CR,30.2,28.9,27.7,25.5,26.4,27.7,CR01,100.0,537.6
1,CR02,CR,25.4,33.1,26.5,30.4,32.3,29.5,CR02,400.0,1557.3
2,CR03,CR,29.5,27.5,25.2,30.9,28.2,28.3,CR03,0.0,772.8
3,CR04,CR,37.1,35.5,32.0,34.1,32.1,34.2,CR04,50.0,1174.2
4,CR05,CR,38.0,29.6,37.5,34.4,38.5,35.6,CR05,0.0,946.4
...,...,...,...,...,...,...,...,...,...,...,...
75,TR16,TR,40.0,49.1,39.3,32.0,44.2,40.9,TR16,0.0,765.0
76,TR17,TR,41.0,56.2,54.5,50.0,51.0,50.5,TR17,50.0,2140.9
77,TR18,TR,44.2,50.1,51.2,48.5,41.0,47.0,TR18,100.0,1253.2
78,TR19,TR,45.2,39.7,38.5,42.0,38.5,40.8,TR19,0.0,1297.3
79,TR20,TR,40.1,43.2,49.5,50.1,47.3,46.0,TR20,200.0,1577.6

In [11]:
import pandas as pd

display(pd.DataFrame(pd.read_csv('dataset/metadata.csv', sep=';'), columns=['ALTURA', 'Cultivar', '1', '2', '3', '4', '5', 'Média', 'PARCELA', 'K2O (kg/ha)', 'MS (kg/ha)']))

,ALTURA,Cultivar,1,2,3,4,5,Média,PARCELA,K2O (kg/ha),MS (kg/ha)
0,CR01M1,CR,30.2,28.9,27.7,25.5,26.4,27.7,CR01,100.0,537.6
1,CR02M1,CR,25.4,33.1,26.5,30.4,32.3,29.5,CR02,400.0,1557.3
2,CR03M1,CR,29.5,27.5,25.2,30.9,28.2,28.3,CR03,0.0,772.8
3,CR04M1,CR,37.1,35.5,32.0,34.1,32.1,34.2,CR04,50.0,1174.2
4,CR05M1,CR,38.0,29.6,37.5,34.4,38.5,35.6,CR05,0.0,946.4
...,...,...,...,...,...,...,...,...,...,...,...
75,TR16M2,TR,40.0,49.1,39.3,32.0,44.2,40.9,TR16,0.0,765.0
76,TR17M2,TR,41.0,56.2,54.5,50.0,51.0,50.5,TR17,50.0,2140.9
77,TR18M2,TR,44.2,50.1,51.2,48.5,41.0,47.0,TR18,100.0,1253.2
78,TR19M2,TR,45.2,39.7,38.5,42.0,38.5,40.8,TR19,0.0,1297.3
79,TR20M2,TR,40.1,43.2,49.5,50.1,47.3,46.0,TR20,200.0,1577.6